# ============================================================================
# GENERAL SETTINGS
# ============================================================================
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g prefix C-b
bind C-b send-prefix
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g status-style 'bg=default'  # transparent

# Window and Pane Settings
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# ============================================================================
# VI MODE SETTINGS
# ============================================================================
set-window-option -g mode-keys vi

# Copy Mode Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ============================================================================
# KEYBINDINGS
# ============================================================================
# Pane Management
bind-key x kill-pane  # skip "kill-pane 1? (y/n)" prompt (cmd+w)
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Session Management
run-shell -b "sleep 2; sesh list > /dev/null 2>&1"
# warm the cache after 2 seconds of new tmux session

bind-key "k" run-shell "sesh connect \"$(
  sesh list --icons -c -z | fzf-tmux -p 90%,90% \
    --no-sort --ansi --border-label ' Wei Heng ' --prompt '⚡  ' \
    --header ' | ^a all | ^d kill | ^f find | ' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:60%' \
    --preview 'sesh preview {}'
)\""
bind -N "last-session (via sesh) " l run-shell "sesh last"

# Configuration Reload
bind r source-file ~/.config/tmux/tmux.conf

# Unbind Keys
unbind-key M-j
unbind-key M-k

# ============================================================================
# PLUGINS
# ============================================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

# Plugin Settings
set -g @catppuccin_flavour 'mocha'

# Initialize TPM (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'

