import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 80
dimensions.lines = 80

decorations = "Buttonless"

startup_mode = "Windowed"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 16

# Create new tmux winow
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

# Close current tmux window
[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

# Open sesh
[[keyboard.bindings]]
chars = "\u0002k"
key = "K"
mods = "Command"

# enter copy mode
[[keyboard.bindings]]
chars = "\u0002["
key = "Y"
mods = "Command"

# Last session
[[keyboard.bindings]]
chars = "\u0002l"
key = "L"
mods = "Command"

# Command + number to select windows
[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"
