import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

dimensions.columns = 80
dimensions.lines = 80

decorations = "Buttonless"

startup_mode = "Windowed"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18
